version: "3.3"
services:
    geth:
        image: ethereum/client-go:release-1.13
        platform: linux/amd64
        environment:
            - DEV_PERIOD
        ports:
            - "8545:8545"
        volumes:
            - ./gethData/geth_data:/geth_data
        entrypoint:
            - geth
            - --rpc.allow-unprotected-txs
            - --http
            - --http.addr
            - "0.0.0.0"
            - --dev
            - --dev.period
            - $DEV_PERIOD
            - --datadir
            - /geth_data
